// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package ru.yandex.practicum.proto.order;

public final class OrderOuterClass {
  private OrderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_yandex_practicum_protobuf_PaymentInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_yandex_practicum_protobuf_PaymentInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_yandex_practicum_protobuf_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_yandex_practicum_protobuf_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\022\034ru.yandex.practicum.proto" +
      "buf\032\037google/protobuf/timestamp.proto\"s\n\013" +
      "PaymentInfo\022\022\n\npayment_id\030\001 \001(\t\022\016\n\006metho" +
      "d\030\002 \001(\t\022\016\n\006amount\030\003 \001(\001\0220\n\014payment_date\030" +
      "\004 \001(\0132\032.google.protobuf.Timestamp\"\211\002\n\005Or" +
      "der\022\020\n\010order_id\030\001 \001(\t\022\022\n\nproduct_id\030\002 \003(" +
      "\t\0229\n\006status\030\003 \001(\0162).ru.yandex.practicum." +
      "protobuf.OrderStatus\022.\n\norder_date\030\004 \001(\013" +
      "2\032.google.protobuf.Timestamp\022A\n\014payment_" +
      "info\030\005 \001(\0132).ru.yandex.practicum.protobu" +
      "f.PaymentInfoH\000\022\027\n\rreturn_reason\030\006 \001(\tH\000" +
      "B\023\n\021payment_or_return*R\n\013OrderStatus\022\013\n\007" +
      "UNKNOWN\020\000\022\013\n\007PENDING\020\001\022\013\n\007SHIPPED\020\002\022\r\n\tD" +
      "ELIVERED\020\003\022\r\n\tCANCELLED\020\004B#\n\037ru.yandex.p" +
      "racticum.proto.orderP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_ru_yandex_practicum_protobuf_PaymentInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_yandex_practicum_protobuf_PaymentInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_yandex_practicum_protobuf_PaymentInfo_descriptor,
        new java.lang.String[] { "PaymentId", "Method", "Amount", "PaymentDate", });
    internal_static_ru_yandex_practicum_protobuf_Order_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_yandex_practicum_protobuf_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_yandex_practicum_protobuf_Order_descriptor,
        new java.lang.String[] { "OrderId", "ProductId", "Status", "OrderDate", "PaymentInfo", "ReturnReason", "PaymentOrReturn", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
