// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package ru.yandex.practicum.proto.order;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.yandex.practicum.protobuf.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string order_id = 1;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 1;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>repeated string product_id = 2;</code>
   * @return A list containing the productId.
   */
  java.util.List<java.lang.String>
      getProductIdList();
  /**
   * <code>repeated string product_id = 2;</code>
   * @return The count of productId.
   */
  int getProductIdCount();
  /**
   * <code>repeated string product_id = 2;</code>
   * @param index The index of the element to return.
   * @return The productId at the given index.
   */
  java.lang.String getProductId(int index);
  /**
   * <code>repeated string product_id = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the productId at the given index.
   */
  com.google.protobuf.ByteString
      getProductIdBytes(int index);

  /**
   * <code>.ru.yandex.practicum.protobuf.OrderStatus status = 3;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.ru.yandex.practicum.protobuf.OrderStatus status = 3;</code>
   * @return The status.
   */
  ru.yandex.practicum.proto.order.OrderStatus getStatus();

  /**
   * <code>.google.protobuf.Timestamp order_date = 4;</code>
   * @return Whether the orderDate field is set.
   */
  boolean hasOrderDate();
  /**
   * <code>.google.protobuf.Timestamp order_date = 4;</code>
   * @return The orderDate.
   */
  com.google.protobuf.Timestamp getOrderDate();
  /**
   * <code>.google.protobuf.Timestamp order_date = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getOrderDateOrBuilder();

  /**
   * <code>.ru.yandex.practicum.protobuf.PaymentInfo payment_info = 5;</code>
   * @return Whether the paymentInfo field is set.
   */
  boolean hasPaymentInfo();
  /**
   * <code>.ru.yandex.practicum.protobuf.PaymentInfo payment_info = 5;</code>
   * @return The paymentInfo.
   */
  ru.yandex.practicum.proto.order.PaymentInfo getPaymentInfo();
  /**
   * <code>.ru.yandex.practicum.protobuf.PaymentInfo payment_info = 5;</code>
   */
  ru.yandex.practicum.proto.order.PaymentInfoOrBuilder getPaymentInfoOrBuilder();

  /**
   * <code>string return_reason = 6;</code>
   * @return Whether the returnReason field is set.
   */
  boolean hasReturnReason();
  /**
   * <code>string return_reason = 6;</code>
   * @return The returnReason.
   */
  java.lang.String getReturnReason();
  /**
   * <code>string return_reason = 6;</code>
   * @return The bytes for returnReason.
   */
  com.google.protobuf.ByteString
      getReturnReasonBytes();

  ru.yandex.practicum.proto.order.Order.PaymentOrReturnCase getPaymentOrReturnCase();
}
