// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package ru.yandex.practicum.proto.order;

/**
 * <pre>
 * Перечисление статусов заказа
 * </pre>
 *
 * Protobuf enum {@code ru.yandex.practicum.protobuf.OrderStatus}
 */
public enum OrderStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <code>PENDING = 1;</code>
   */
  PENDING(1),
  /**
   * <code>SHIPPED = 2;</code>
   */
  SHIPPED(2),
  /**
   * <code>DELIVERED = 3;</code>
   */
  DELIVERED(3),
  /**
   * <code>CANCELLED = 4;</code>
   */
  CANCELLED(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <code>PENDING = 1;</code>
   */
  public static final int PENDING_VALUE = 1;
  /**
   * <code>SHIPPED = 2;</code>
   */
  public static final int SHIPPED_VALUE = 2;
  /**
   * <code>DELIVERED = 3;</code>
   */
  public static final int DELIVERED_VALUE = 3;
  /**
   * <code>CANCELLED = 4;</code>
   */
  public static final int CANCELLED_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OrderStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OrderStatus forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return PENDING;
      case 2: return SHIPPED;
      case 3: return DELIVERED;
      case 4: return CANCELLED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OrderStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OrderStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OrderStatus>() {
          public OrderStatus findValueByNumber(int number) {
            return OrderStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ru.yandex.practicum.proto.order.OrderOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final OrderStatus[] VALUES = values();

  public static OrderStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OrderStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ru.yandex.practicum.protobuf.OrderStatus)
}

