// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package ru.yandex.practicum.proto.order;

/**
 * <pre>
 * Заказ
 * </pre>
 *
 * Protobuf type {@code ru.yandex.practicum.protobuf.Order}
 */
public final class Order extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.yandex.practicum.protobuf.Order)
    OrderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Order.newBuilder() to construct.
  private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Order() {
    orderId_ = "";
    productId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    status_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Order();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.yandex.practicum.proto.order.OrderOuterClass.internal_static_ru_yandex_practicum_protobuf_Order_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.yandex.practicum.proto.order.OrderOuterClass.internal_static_ru_yandex_practicum_protobuf_Order_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.yandex.practicum.proto.order.Order.class, ru.yandex.practicum.proto.order.Order.Builder.class);
  }

  private int paymentOrReturnCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object paymentOrReturn_;
  public enum PaymentOrReturnCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    PAYMENT_INFO(5),
    RETURN_REASON(6),
    PAYMENTORRETURN_NOT_SET(0);
    private final int value;
    private PaymentOrReturnCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PaymentOrReturnCase valueOf(int value) {
      return forNumber(value);
    }

    public static PaymentOrReturnCase forNumber(int value) {
      switch (value) {
        case 5: return PAYMENT_INFO;
        case 6: return RETURN_REASON;
        case 0: return PAYMENTORRETURN_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PaymentOrReturnCase
  getPaymentOrReturnCase() {
    return PaymentOrReturnCase.forNumber(
        paymentOrReturnCase_);
  }

  public static final int ORDER_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object orderId_ = "";
  /**
   * <code>string order_id = 1;</code>
   * @return The orderId.
   */
  @java.lang.Override
  public java.lang.String getOrderId() {
    java.lang.Object ref = orderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderId_ = s;
      return s;
    }
  }
  /**
   * <code>string order_id = 1;</code>
   * @return The bytes for orderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrderIdBytes() {
    java.lang.Object ref = orderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList productId_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string product_id = 2;</code>
   * @return A list containing the productId.
   */
  public com.google.protobuf.ProtocolStringList
      getProductIdList() {
    return productId_;
  }
  /**
   * <code>repeated string product_id = 2;</code>
   * @return The count of productId.
   */
  public int getProductIdCount() {
    return productId_.size();
  }
  /**
   * <code>repeated string product_id = 2;</code>
   * @param index The index of the element to return.
   * @return The productId at the given index.
   */
  public java.lang.String getProductId(int index) {
    return productId_.get(index);
  }
  /**
   * <code>repeated string product_id = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the productId at the given index.
   */
  public com.google.protobuf.ByteString
      getProductIdBytes(int index) {
    return productId_.getByteString(index);
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private int status_ = 0;
  /**
   * <code>.ru.yandex.practicum.protobuf.OrderStatus status = 3;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.ru.yandex.practicum.protobuf.OrderStatus status = 3;</code>
   * @return The status.
   */
  @java.lang.Override public ru.yandex.practicum.proto.order.OrderStatus getStatus() {
    ru.yandex.practicum.proto.order.OrderStatus result = ru.yandex.practicum.proto.order.OrderStatus.forNumber(status_);
    return result == null ? ru.yandex.practicum.proto.order.OrderStatus.UNRECOGNIZED : result;
  }

  public static final int ORDER_DATE_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp orderDate_;
  /**
   * <code>.google.protobuf.Timestamp order_date = 4;</code>
   * @return Whether the orderDate field is set.
   */
  @java.lang.Override
  public boolean hasOrderDate() {
    return orderDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp order_date = 4;</code>
   * @return The orderDate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getOrderDate() {
    return orderDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : orderDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp order_date = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getOrderDateOrBuilder() {
    return orderDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : orderDate_;
  }

  public static final int PAYMENT_INFO_FIELD_NUMBER = 5;
  /**
   * <code>.ru.yandex.practicum.protobuf.PaymentInfo payment_info = 5;</code>
   * @return Whether the paymentInfo field is set.
   */
  @java.lang.Override
  public boolean hasPaymentInfo() {
    return paymentOrReturnCase_ == 5;
  }
  /**
   * <code>.ru.yandex.practicum.protobuf.PaymentInfo payment_info = 5;</code>
   * @return The paymentInfo.
   */
  @java.lang.Override
  public ru.yandex.practicum.proto.order.PaymentInfo getPaymentInfo() {
    if (paymentOrReturnCase_ == 5) {
       return (ru.yandex.practicum.proto.order.PaymentInfo) paymentOrReturn_;
    }
    return ru.yandex.practicum.proto.order.PaymentInfo.getDefaultInstance();
  }
  /**
   * <code>.ru.yandex.practicum.protobuf.PaymentInfo payment_info = 5;</code>
   */
  @java.lang.Override
  public ru.yandex.practicum.proto.order.PaymentInfoOrBuilder getPaymentInfoOrBuilder() {
    if (paymentOrReturnCase_ == 5) {
       return (ru.yandex.practicum.proto.order.PaymentInfo) paymentOrReturn_;
    }
    return ru.yandex.practicum.proto.order.PaymentInfo.getDefaultInstance();
  }

  public static final int RETURN_REASON_FIELD_NUMBER = 6;
  /**
   * <code>string return_reason = 6;</code>
   * @return Whether the returnReason field is set.
   */
  public boolean hasReturnReason() {
    return paymentOrReturnCase_ == 6;
  }
  /**
   * <code>string return_reason = 6;</code>
   * @return The returnReason.
   */
  public java.lang.String getReturnReason() {
    java.lang.Object ref = "";
    if (paymentOrReturnCase_ == 6) {
      ref = paymentOrReturn_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (paymentOrReturnCase_ == 6) {
        paymentOrReturn_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string return_reason = 6;</code>
   * @return The bytes for returnReason.
   */
  public com.google.protobuf.ByteString
      getReturnReasonBytes() {
    java.lang.Object ref = "";
    if (paymentOrReturnCase_ == 6) {
      ref = paymentOrReturn_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (paymentOrReturnCase_ == 6) {
        paymentOrReturn_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orderId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, orderId_);
    }
    for (int i = 0; i < productId_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productId_.getRaw(i));
    }
    if (status_ != ru.yandex.practicum.proto.order.OrderStatus.UNKNOWN.getNumber()) {
      output.writeEnum(3, status_);
    }
    if (orderDate_ != null) {
      output.writeMessage(4, getOrderDate());
    }
    if (paymentOrReturnCase_ == 5) {
      output.writeMessage(5, (ru.yandex.practicum.proto.order.PaymentInfo) paymentOrReturn_);
    }
    if (paymentOrReturnCase_ == 6) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, paymentOrReturn_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orderId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, orderId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < productId_.size(); i++) {
        dataSize += computeStringSizeNoTag(productId_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getProductIdList().size();
    }
    if (status_ != ru.yandex.practicum.proto.order.OrderStatus.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, status_);
    }
    if (orderDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getOrderDate());
    }
    if (paymentOrReturnCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (ru.yandex.practicum.proto.order.PaymentInfo) paymentOrReturn_);
    }
    if (paymentOrReturnCase_ == 6) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, paymentOrReturn_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.yandex.practicum.proto.order.Order)) {
      return super.equals(obj);
    }
    ru.yandex.practicum.proto.order.Order other = (ru.yandex.practicum.proto.order.Order) obj;

    if (!getOrderId()
        .equals(other.getOrderId())) return false;
    if (!getProductIdList()
        .equals(other.getProductIdList())) return false;
    if (status_ != other.status_) return false;
    if (hasOrderDate() != other.hasOrderDate()) return false;
    if (hasOrderDate()) {
      if (!getOrderDate()
          .equals(other.getOrderDate())) return false;
    }
    if (!getPaymentOrReturnCase().equals(other.getPaymentOrReturnCase())) return false;
    switch (paymentOrReturnCase_) {
      case 5:
        if (!getPaymentInfo()
            .equals(other.getPaymentInfo())) return false;
        break;
      case 6:
        if (!getReturnReason()
            .equals(other.getReturnReason())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOrderId().hashCode();
    if (getProductIdCount() > 0) {
      hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getProductIdList().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasOrderDate()) {
      hash = (37 * hash) + ORDER_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getOrderDate().hashCode();
    }
    switch (paymentOrReturnCase_) {
      case 5:
        hash = (37 * hash) + PAYMENT_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getPaymentInfo().hashCode();
        break;
      case 6:
        hash = (37 * hash) + RETURN_REASON_FIELD_NUMBER;
        hash = (53 * hash) + getReturnReason().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.yandex.practicum.proto.order.Order parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.yandex.practicum.proto.order.Order parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.yandex.practicum.proto.order.Order parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.yandex.practicum.proto.order.Order parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.yandex.practicum.proto.order.Order parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.yandex.practicum.proto.order.Order parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.yandex.practicum.proto.order.Order parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.yandex.practicum.proto.order.Order parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ru.yandex.practicum.proto.order.Order parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ru.yandex.practicum.proto.order.Order parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.yandex.practicum.proto.order.Order parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.yandex.practicum.proto.order.Order parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.yandex.practicum.proto.order.Order prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Заказ
   * </pre>
   *
   * Protobuf type {@code ru.yandex.practicum.protobuf.Order}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.yandex.practicum.protobuf.Order)
      ru.yandex.practicum.proto.order.OrderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.yandex.practicum.proto.order.OrderOuterClass.internal_static_ru_yandex_practicum_protobuf_Order_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.yandex.practicum.proto.order.OrderOuterClass.internal_static_ru_yandex_practicum_protobuf_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.yandex.practicum.proto.order.Order.class, ru.yandex.practicum.proto.order.Order.Builder.class);
    }

    // Construct using ru.yandex.practicum.proto.order.Order.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      orderId_ = "";
      productId_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      status_ = 0;
      orderDate_ = null;
      if (orderDateBuilder_ != null) {
        orderDateBuilder_.dispose();
        orderDateBuilder_ = null;
      }
      if (paymentInfoBuilder_ != null) {
        paymentInfoBuilder_.clear();
      }
      paymentOrReturnCase_ = 0;
      paymentOrReturn_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.yandex.practicum.proto.order.OrderOuterClass.internal_static_ru_yandex_practicum_protobuf_Order_descriptor;
    }

    @java.lang.Override
    public ru.yandex.practicum.proto.order.Order getDefaultInstanceForType() {
      return ru.yandex.practicum.proto.order.Order.getDefaultInstance();
    }

    @java.lang.Override
    public ru.yandex.practicum.proto.order.Order build() {
      ru.yandex.practicum.proto.order.Order result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.yandex.practicum.proto.order.Order buildPartial() {
      ru.yandex.practicum.proto.order.Order result = new ru.yandex.practicum.proto.order.Order(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(ru.yandex.practicum.proto.order.Order result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.orderId_ = orderId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        productId_.makeImmutable();
        result.productId_ = productId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.orderDate_ = orderDateBuilder_ == null
            ? orderDate_
            : orderDateBuilder_.build();
      }
    }

    private void buildPartialOneofs(ru.yandex.practicum.proto.order.Order result) {
      result.paymentOrReturnCase_ = paymentOrReturnCase_;
      result.paymentOrReturn_ = this.paymentOrReturn_;
      if (paymentOrReturnCase_ == 5 &&
          paymentInfoBuilder_ != null) {
        result.paymentOrReturn_ = paymentInfoBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.yandex.practicum.proto.order.Order) {
        return mergeFrom((ru.yandex.practicum.proto.order.Order)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.yandex.practicum.proto.order.Order other) {
      if (other == ru.yandex.practicum.proto.order.Order.getDefaultInstance()) return this;
      if (!other.getOrderId().isEmpty()) {
        orderId_ = other.orderId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.productId_.isEmpty()) {
        if (productId_.isEmpty()) {
          productId_ = other.productId_;
          bitField0_ |= 0x00000002;
        } else {
          ensureProductIdIsMutable();
          productId_.addAll(other.productId_);
        }
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasOrderDate()) {
        mergeOrderDate(other.getOrderDate());
      }
      switch (other.getPaymentOrReturnCase()) {
        case PAYMENT_INFO: {
          mergePaymentInfo(other.getPaymentInfo());
          break;
        }
        case RETURN_REASON: {
          paymentOrReturnCase_ = 6;
          paymentOrReturn_ = other.paymentOrReturn_;
          onChanged();
          break;
        }
        case PAYMENTORRETURN_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              orderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureProductIdIsMutable();
              productId_.add(s);
              break;
            } // case 18
            case 24: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getOrderDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getPaymentInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              paymentOrReturnCase_ = 5;
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              paymentOrReturnCase_ = 6;
              paymentOrReturn_ = s;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int paymentOrReturnCase_ = 0;
    private java.lang.Object paymentOrReturn_;
    public PaymentOrReturnCase
        getPaymentOrReturnCase() {
      return PaymentOrReturnCase.forNumber(
          paymentOrReturnCase_);
    }

    public Builder clearPaymentOrReturn() {
      paymentOrReturnCase_ = 0;
      paymentOrReturn_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object orderId_ = "";
    /**
     * <code>string order_id = 1;</code>
     * @return The orderId.
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string order_id = 1;</code>
     * @return The bytes for orderId.
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string order_id = 1;</code>
     * @param value The orderId to set.
     * @return This builder for chaining.
     */
    public Builder setOrderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      orderId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string order_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderId() {
      orderId_ = getDefaultInstance().getOrderId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string order_id = 1;</code>
     * @param value The bytes for orderId to set.
     * @return This builder for chaining.
     */
    public Builder setOrderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      orderId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList productId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureProductIdIsMutable() {
      if (!productId_.isModifiable()) {
        productId_ = new com.google.protobuf.LazyStringArrayList(productId_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string product_id = 2;</code>
     * @return A list containing the productId.
     */
    public com.google.protobuf.ProtocolStringList
        getProductIdList() {
      productId_.makeImmutable();
      return productId_;
    }
    /**
     * <code>repeated string product_id = 2;</code>
     * @return The count of productId.
     */
    public int getProductIdCount() {
      return productId_.size();
    }
    /**
     * <code>repeated string product_id = 2;</code>
     * @param index The index of the element to return.
     * @return The productId at the given index.
     */
    public java.lang.String getProductId(int index) {
      return productId_.get(index);
    }
    /**
     * <code>repeated string product_id = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the productId at the given index.
     */
    public com.google.protobuf.ByteString
        getProductIdBytes(int index) {
      return productId_.getByteString(index);
    }
    /**
     * <code>repeated string product_id = 2;</code>
     * @param index The index to set the value at.
     * @param value The productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductId(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureProductIdIsMutable();
      productId_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string product_id = 2;</code>
     * @param value The productId to add.
     * @return This builder for chaining.
     */
    public Builder addProductId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureProductIdIsMutable();
      productId_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string product_id = 2;</code>
     * @param values The productId to add.
     * @return This builder for chaining.
     */
    public Builder addAllProductId(
        java.lang.Iterable<java.lang.String> values) {
      ensureProductIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, productId_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string product_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductId() {
      productId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string product_id = 2;</code>
     * @param value The bytes of the productId to add.
     * @return This builder for chaining.
     */
    public Builder addProductIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureProductIdIsMutable();
      productId_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.ru.yandex.practicum.protobuf.OrderStatus status = 3;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.ru.yandex.practicum.protobuf.OrderStatus status = 3;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.ru.yandex.practicum.protobuf.OrderStatus status = 3;</code>
     * @return The status.
     */
    @java.lang.Override
    public ru.yandex.practicum.proto.order.OrderStatus getStatus() {
      ru.yandex.practicum.proto.order.OrderStatus result = ru.yandex.practicum.proto.order.OrderStatus.forNumber(status_);
      return result == null ? ru.yandex.practicum.proto.order.OrderStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.ru.yandex.practicum.protobuf.OrderStatus status = 3;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(ru.yandex.practicum.proto.order.OrderStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ru.yandex.practicum.protobuf.OrderStatus status = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000004);
      status_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp orderDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> orderDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp order_date = 4;</code>
     * @return Whether the orderDate field is set.
     */
    public boolean hasOrderDate() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp order_date = 4;</code>
     * @return The orderDate.
     */
    public com.google.protobuf.Timestamp getOrderDate() {
      if (orderDateBuilder_ == null) {
        return orderDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : orderDate_;
      } else {
        return orderDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp order_date = 4;</code>
     */
    public Builder setOrderDate(com.google.protobuf.Timestamp value) {
      if (orderDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        orderDate_ = value;
      } else {
        orderDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp order_date = 4;</code>
     */
    public Builder setOrderDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (orderDateBuilder_ == null) {
        orderDate_ = builderForValue.build();
      } else {
        orderDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp order_date = 4;</code>
     */
    public Builder mergeOrderDate(com.google.protobuf.Timestamp value) {
      if (orderDateBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          orderDate_ != null &&
          orderDate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getOrderDateBuilder().mergeFrom(value);
        } else {
          orderDate_ = value;
        }
      } else {
        orderDateBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp order_date = 4;</code>
     */
    public Builder clearOrderDate() {
      bitField0_ = (bitField0_ & ~0x00000008);
      orderDate_ = null;
      if (orderDateBuilder_ != null) {
        orderDateBuilder_.dispose();
        orderDateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp order_date = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getOrderDateBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getOrderDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp order_date = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getOrderDateOrBuilder() {
      if (orderDateBuilder_ != null) {
        return orderDateBuilder_.getMessageOrBuilder();
      } else {
        return orderDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : orderDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp order_date = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getOrderDateFieldBuilder() {
      if (orderDateBuilder_ == null) {
        orderDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getOrderDate(),
                getParentForChildren(),
                isClean());
        orderDate_ = null;
      }
      return orderDateBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.yandex.practicum.proto.order.PaymentInfo, ru.yandex.practicum.proto.order.PaymentInfo.Builder, ru.yandex.practicum.proto.order.PaymentInfoOrBuilder> paymentInfoBuilder_;
    /**
     * <code>.ru.yandex.practicum.protobuf.PaymentInfo payment_info = 5;</code>
     * @return Whether the paymentInfo field is set.
     */
    @java.lang.Override
    public boolean hasPaymentInfo() {
      return paymentOrReturnCase_ == 5;
    }
    /**
     * <code>.ru.yandex.practicum.protobuf.PaymentInfo payment_info = 5;</code>
     * @return The paymentInfo.
     */
    @java.lang.Override
    public ru.yandex.practicum.proto.order.PaymentInfo getPaymentInfo() {
      if (paymentInfoBuilder_ == null) {
        if (paymentOrReturnCase_ == 5) {
          return (ru.yandex.practicum.proto.order.PaymentInfo) paymentOrReturn_;
        }
        return ru.yandex.practicum.proto.order.PaymentInfo.getDefaultInstance();
      } else {
        if (paymentOrReturnCase_ == 5) {
          return paymentInfoBuilder_.getMessage();
        }
        return ru.yandex.practicum.proto.order.PaymentInfo.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.yandex.practicum.protobuf.PaymentInfo payment_info = 5;</code>
     */
    public Builder setPaymentInfo(ru.yandex.practicum.proto.order.PaymentInfo value) {
      if (paymentInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        paymentOrReturn_ = value;
        onChanged();
      } else {
        paymentInfoBuilder_.setMessage(value);
      }
      paymentOrReturnCase_ = 5;
      return this;
    }
    /**
     * <code>.ru.yandex.practicum.protobuf.PaymentInfo payment_info = 5;</code>
     */
    public Builder setPaymentInfo(
        ru.yandex.practicum.proto.order.PaymentInfo.Builder builderForValue) {
      if (paymentInfoBuilder_ == null) {
        paymentOrReturn_ = builderForValue.build();
        onChanged();
      } else {
        paymentInfoBuilder_.setMessage(builderForValue.build());
      }
      paymentOrReturnCase_ = 5;
      return this;
    }
    /**
     * <code>.ru.yandex.practicum.protobuf.PaymentInfo payment_info = 5;</code>
     */
    public Builder mergePaymentInfo(ru.yandex.practicum.proto.order.PaymentInfo value) {
      if (paymentInfoBuilder_ == null) {
        if (paymentOrReturnCase_ == 5 &&
            paymentOrReturn_ != ru.yandex.practicum.proto.order.PaymentInfo.getDefaultInstance()) {
          paymentOrReturn_ = ru.yandex.practicum.proto.order.PaymentInfo.newBuilder((ru.yandex.practicum.proto.order.PaymentInfo) paymentOrReturn_)
              .mergeFrom(value).buildPartial();
        } else {
          paymentOrReturn_ = value;
        }
        onChanged();
      } else {
        if (paymentOrReturnCase_ == 5) {
          paymentInfoBuilder_.mergeFrom(value);
        } else {
          paymentInfoBuilder_.setMessage(value);
        }
      }
      paymentOrReturnCase_ = 5;
      return this;
    }
    /**
     * <code>.ru.yandex.practicum.protobuf.PaymentInfo payment_info = 5;</code>
     */
    public Builder clearPaymentInfo() {
      if (paymentInfoBuilder_ == null) {
        if (paymentOrReturnCase_ == 5) {
          paymentOrReturnCase_ = 0;
          paymentOrReturn_ = null;
          onChanged();
        }
      } else {
        if (paymentOrReturnCase_ == 5) {
          paymentOrReturnCase_ = 0;
          paymentOrReturn_ = null;
        }
        paymentInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.yandex.practicum.protobuf.PaymentInfo payment_info = 5;</code>
     */
    public ru.yandex.practicum.proto.order.PaymentInfo.Builder getPaymentInfoBuilder() {
      return getPaymentInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.yandex.practicum.protobuf.PaymentInfo payment_info = 5;</code>
     */
    @java.lang.Override
    public ru.yandex.practicum.proto.order.PaymentInfoOrBuilder getPaymentInfoOrBuilder() {
      if ((paymentOrReturnCase_ == 5) && (paymentInfoBuilder_ != null)) {
        return paymentInfoBuilder_.getMessageOrBuilder();
      } else {
        if (paymentOrReturnCase_ == 5) {
          return (ru.yandex.practicum.proto.order.PaymentInfo) paymentOrReturn_;
        }
        return ru.yandex.practicum.proto.order.PaymentInfo.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.yandex.practicum.protobuf.PaymentInfo payment_info = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.yandex.practicum.proto.order.PaymentInfo, ru.yandex.practicum.proto.order.PaymentInfo.Builder, ru.yandex.practicum.proto.order.PaymentInfoOrBuilder> 
        getPaymentInfoFieldBuilder() {
      if (paymentInfoBuilder_ == null) {
        if (!(paymentOrReturnCase_ == 5)) {
          paymentOrReturn_ = ru.yandex.practicum.proto.order.PaymentInfo.getDefaultInstance();
        }
        paymentInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.yandex.practicum.proto.order.PaymentInfo, ru.yandex.practicum.proto.order.PaymentInfo.Builder, ru.yandex.practicum.proto.order.PaymentInfoOrBuilder>(
                (ru.yandex.practicum.proto.order.PaymentInfo) paymentOrReturn_,
                getParentForChildren(),
                isClean());
        paymentOrReturn_ = null;
      }
      paymentOrReturnCase_ = 5;
      onChanged();
      return paymentInfoBuilder_;
    }

    /**
     * <code>string return_reason = 6;</code>
     * @return Whether the returnReason field is set.
     */
    @java.lang.Override
    public boolean hasReturnReason() {
      return paymentOrReturnCase_ == 6;
    }
    /**
     * <code>string return_reason = 6;</code>
     * @return The returnReason.
     */
    @java.lang.Override
    public java.lang.String getReturnReason() {
      java.lang.Object ref = "";
      if (paymentOrReturnCase_ == 6) {
        ref = paymentOrReturn_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (paymentOrReturnCase_ == 6) {
          paymentOrReturn_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string return_reason = 6;</code>
     * @return The bytes for returnReason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReturnReasonBytes() {
      java.lang.Object ref = "";
      if (paymentOrReturnCase_ == 6) {
        ref = paymentOrReturn_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (paymentOrReturnCase_ == 6) {
          paymentOrReturn_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string return_reason = 6;</code>
     * @param value The returnReason to set.
     * @return This builder for chaining.
     */
    public Builder setReturnReason(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      paymentOrReturnCase_ = 6;
      paymentOrReturn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string return_reason = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearReturnReason() {
      if (paymentOrReturnCase_ == 6) {
        paymentOrReturnCase_ = 0;
        paymentOrReturn_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string return_reason = 6;</code>
     * @param value The bytes for returnReason to set.
     * @return This builder for chaining.
     */
    public Builder setReturnReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      paymentOrReturnCase_ = 6;
      paymentOrReturn_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.yandex.practicum.protobuf.Order)
  }

  // @@protoc_insertion_point(class_scope:ru.yandex.practicum.protobuf.Order)
  private static final ru.yandex.practicum.proto.order.Order DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.yandex.practicum.proto.order.Order();
  }

  public static ru.yandex.practicum.proto.order.Order getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Order>
      PARSER = new com.google.protobuf.AbstractParser<Order>() {
    @java.lang.Override
    public Order parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Order> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Order> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.yandex.practicum.proto.order.Order getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

