// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package ru.yandex.practicum.proto.order;

/**
 * <pre>
 * Информация о платеже
 * </pre>
 *
 * Protobuf type {@code ru.yandex.practicum.protobuf.PaymentInfo}
 */
public final class PaymentInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.yandex.practicum.protobuf.PaymentInfo)
    PaymentInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PaymentInfo.newBuilder() to construct.
  private PaymentInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PaymentInfo() {
    paymentId_ = "";
    method_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PaymentInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.yandex.practicum.proto.order.OrderOuterClass.internal_static_ru_yandex_practicum_protobuf_PaymentInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.yandex.practicum.proto.order.OrderOuterClass.internal_static_ru_yandex_practicum_protobuf_PaymentInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.yandex.practicum.proto.order.PaymentInfo.class, ru.yandex.practicum.proto.order.PaymentInfo.Builder.class);
  }

  public static final int PAYMENT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object paymentId_ = "";
  /**
   * <code>string payment_id = 1;</code>
   * @return The paymentId.
   */
  @java.lang.Override
  public java.lang.String getPaymentId() {
    java.lang.Object ref = paymentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      paymentId_ = s;
      return s;
    }
  }
  /**
   * <code>string payment_id = 1;</code>
   * @return The bytes for paymentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPaymentIdBytes() {
    java.lang.Object ref = paymentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      paymentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHOD_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object method_ = "";
  /**
   * <code>string method = 2;</code>
   * @return The method.
   */
  @java.lang.Override
  public java.lang.String getMethod() {
    java.lang.Object ref = method_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      method_ = s;
      return s;
    }
  }
  /**
   * <code>string method = 2;</code>
   * @return The bytes for method.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMethodBytes() {
    java.lang.Object ref = method_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      method_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 3;
  private double amount_ = 0D;
  /**
   * <pre>
   * 64-битное число с плавающей точкой
   * </pre>
   *
   * <code>double amount = 3;</code>
   * @return The amount.
   */
  @java.lang.Override
  public double getAmount() {
    return amount_;
  }

  public static final int PAYMENT_DATE_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp paymentDate_;
  /**
   * <code>.google.protobuf.Timestamp payment_date = 4;</code>
   * @return Whether the paymentDate field is set.
   */
  @java.lang.Override
  public boolean hasPaymentDate() {
    return paymentDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp payment_date = 4;</code>
   * @return The paymentDate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getPaymentDate() {
    return paymentDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : paymentDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp payment_date = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getPaymentDateOrBuilder() {
    return paymentDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : paymentDate_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(paymentId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, paymentId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(method_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, method_);
    }
    if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
      output.writeDouble(3, amount_);
    }
    if (paymentDate_ != null) {
      output.writeMessage(4, getPaymentDate());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(paymentId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, paymentId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(method_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, method_);
    }
    if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, amount_);
    }
    if (paymentDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getPaymentDate());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.yandex.practicum.proto.order.PaymentInfo)) {
      return super.equals(obj);
    }
    ru.yandex.practicum.proto.order.PaymentInfo other = (ru.yandex.practicum.proto.order.PaymentInfo) obj;

    if (!getPaymentId()
        .equals(other.getPaymentId())) return false;
    if (!getMethod()
        .equals(other.getMethod())) return false;
    if (java.lang.Double.doubleToLongBits(getAmount())
        != java.lang.Double.doubleToLongBits(
            other.getAmount())) return false;
    if (hasPaymentDate() != other.hasPaymentDate()) return false;
    if (hasPaymentDate()) {
      if (!getPaymentDate()
          .equals(other.getPaymentDate())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PAYMENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPaymentId().hashCode();
    hash = (37 * hash) + METHOD_FIELD_NUMBER;
    hash = (53 * hash) + getMethod().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAmount()));
    if (hasPaymentDate()) {
      hash = (37 * hash) + PAYMENT_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getPaymentDate().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.yandex.practicum.proto.order.PaymentInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.yandex.practicum.proto.order.PaymentInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.yandex.practicum.proto.order.PaymentInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.yandex.practicum.proto.order.PaymentInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.yandex.practicum.proto.order.PaymentInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.yandex.practicum.proto.order.PaymentInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.yandex.practicum.proto.order.PaymentInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.yandex.practicum.proto.order.PaymentInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ru.yandex.practicum.proto.order.PaymentInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ru.yandex.practicum.proto.order.PaymentInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.yandex.practicum.proto.order.PaymentInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.yandex.practicum.proto.order.PaymentInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.yandex.practicum.proto.order.PaymentInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Информация о платеже
   * </pre>
   *
   * Protobuf type {@code ru.yandex.practicum.protobuf.PaymentInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.yandex.practicum.protobuf.PaymentInfo)
      ru.yandex.practicum.proto.order.PaymentInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.yandex.practicum.proto.order.OrderOuterClass.internal_static_ru_yandex_practicum_protobuf_PaymentInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.yandex.practicum.proto.order.OrderOuterClass.internal_static_ru_yandex_practicum_protobuf_PaymentInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.yandex.practicum.proto.order.PaymentInfo.class, ru.yandex.practicum.proto.order.PaymentInfo.Builder.class);
    }

    // Construct using ru.yandex.practicum.proto.order.PaymentInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      paymentId_ = "";
      method_ = "";
      amount_ = 0D;
      paymentDate_ = null;
      if (paymentDateBuilder_ != null) {
        paymentDateBuilder_.dispose();
        paymentDateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.yandex.practicum.proto.order.OrderOuterClass.internal_static_ru_yandex_practicum_protobuf_PaymentInfo_descriptor;
    }

    @java.lang.Override
    public ru.yandex.practicum.proto.order.PaymentInfo getDefaultInstanceForType() {
      return ru.yandex.practicum.proto.order.PaymentInfo.getDefaultInstance();
    }

    @java.lang.Override
    public ru.yandex.practicum.proto.order.PaymentInfo build() {
      ru.yandex.practicum.proto.order.PaymentInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.yandex.practicum.proto.order.PaymentInfo buildPartial() {
      ru.yandex.practicum.proto.order.PaymentInfo result = new ru.yandex.practicum.proto.order.PaymentInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ru.yandex.practicum.proto.order.PaymentInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.paymentId_ = paymentId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.method_ = method_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.amount_ = amount_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.paymentDate_ = paymentDateBuilder_ == null
            ? paymentDate_
            : paymentDateBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.yandex.practicum.proto.order.PaymentInfo) {
        return mergeFrom((ru.yandex.practicum.proto.order.PaymentInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.yandex.practicum.proto.order.PaymentInfo other) {
      if (other == ru.yandex.practicum.proto.order.PaymentInfo.getDefaultInstance()) return this;
      if (!other.getPaymentId().isEmpty()) {
        paymentId_ = other.paymentId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getMethod().isEmpty()) {
        method_ = other.method_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getAmount() != 0D) {
        setAmount(other.getAmount());
      }
      if (other.hasPaymentDate()) {
        mergePaymentDate(other.getPaymentDate());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              paymentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              method_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              amount_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 34: {
              input.readMessage(
                  getPaymentDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object paymentId_ = "";
    /**
     * <code>string payment_id = 1;</code>
     * @return The paymentId.
     */
    public java.lang.String getPaymentId() {
      java.lang.Object ref = paymentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        paymentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string payment_id = 1;</code>
     * @return The bytes for paymentId.
     */
    public com.google.protobuf.ByteString
        getPaymentIdBytes() {
      java.lang.Object ref = paymentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paymentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string payment_id = 1;</code>
     * @param value The paymentId to set.
     * @return This builder for chaining.
     */
    public Builder setPaymentId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      paymentId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string payment_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaymentId() {
      paymentId_ = getDefaultInstance().getPaymentId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string payment_id = 1;</code>
     * @param value The bytes for paymentId to set.
     * @return This builder for chaining.
     */
    public Builder setPaymentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      paymentId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object method_ = "";
    /**
     * <code>string method = 2;</code>
     * @return The method.
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string method = 2;</code>
     * @return The bytes for method.
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string method = 2;</code>
     * @param value The method to set.
     * @return This builder for chaining.
     */
    public Builder setMethod(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      method_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string method = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethod() {
      method_ = getDefaultInstance().getMethod();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string method = 2;</code>
     * @param value The bytes for method to set.
     * @return This builder for chaining.
     */
    public Builder setMethodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      method_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private double amount_ ;
    /**
     * <pre>
     * 64-битное число с плавающей точкой
     * </pre>
     *
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    @java.lang.Override
    public double getAmount() {
      return amount_;
    }
    /**
     * <pre>
     * 64-битное число с плавающей точкой
     * </pre>
     *
     * <code>double amount = 3;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(double value) {

      amount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 64-битное число с плавающей точкой
     * </pre>
     *
     * <code>double amount = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      amount_ = 0D;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp paymentDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> paymentDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp payment_date = 4;</code>
     * @return Whether the paymentDate field is set.
     */
    public boolean hasPaymentDate() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp payment_date = 4;</code>
     * @return The paymentDate.
     */
    public com.google.protobuf.Timestamp getPaymentDate() {
      if (paymentDateBuilder_ == null) {
        return paymentDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : paymentDate_;
      } else {
        return paymentDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp payment_date = 4;</code>
     */
    public Builder setPaymentDate(com.google.protobuf.Timestamp value) {
      if (paymentDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        paymentDate_ = value;
      } else {
        paymentDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp payment_date = 4;</code>
     */
    public Builder setPaymentDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (paymentDateBuilder_ == null) {
        paymentDate_ = builderForValue.build();
      } else {
        paymentDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp payment_date = 4;</code>
     */
    public Builder mergePaymentDate(com.google.protobuf.Timestamp value) {
      if (paymentDateBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          paymentDate_ != null &&
          paymentDate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getPaymentDateBuilder().mergeFrom(value);
        } else {
          paymentDate_ = value;
        }
      } else {
        paymentDateBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp payment_date = 4;</code>
     */
    public Builder clearPaymentDate() {
      bitField0_ = (bitField0_ & ~0x00000008);
      paymentDate_ = null;
      if (paymentDateBuilder_ != null) {
        paymentDateBuilder_.dispose();
        paymentDateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp payment_date = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getPaymentDateBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getPaymentDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp payment_date = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getPaymentDateOrBuilder() {
      if (paymentDateBuilder_ != null) {
        return paymentDateBuilder_.getMessageOrBuilder();
      } else {
        return paymentDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : paymentDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp payment_date = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getPaymentDateFieldBuilder() {
      if (paymentDateBuilder_ == null) {
        paymentDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getPaymentDate(),
                getParentForChildren(),
                isClean());
        paymentDate_ = null;
      }
      return paymentDateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.yandex.practicum.protobuf.PaymentInfo)
  }

  // @@protoc_insertion_point(class_scope:ru.yandex.practicum.protobuf.PaymentInfo)
  private static final ru.yandex.practicum.proto.order.PaymentInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.yandex.practicum.proto.order.PaymentInfo();
  }

  public static ru.yandex.practicum.proto.order.PaymentInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PaymentInfo>
      PARSER = new com.google.protobuf.AbstractParser<PaymentInfo>() {
    @java.lang.Override
    public PaymentInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PaymentInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PaymentInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.yandex.practicum.proto.order.PaymentInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

