// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package ru.yandex.practicum.proto.order;

public interface PaymentInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.yandex.practicum.protobuf.PaymentInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string payment_id = 1;</code>
   * @return The paymentId.
   */
  java.lang.String getPaymentId();
  /**
   * <code>string payment_id = 1;</code>
   * @return The bytes for paymentId.
   */
  com.google.protobuf.ByteString
      getPaymentIdBytes();

  /**
   * <code>string method = 2;</code>
   * @return The method.
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 2;</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <pre>
   * 64-битное число с плавающей точкой
   * </pre>
   *
   * <code>double amount = 3;</code>
   * @return The amount.
   */
  double getAmount();

  /**
   * <code>.google.protobuf.Timestamp payment_date = 4;</code>
   * @return Whether the paymentDate field is set.
   */
  boolean hasPaymentDate();
  /**
   * <code>.google.protobuf.Timestamp payment_date = 4;</code>
   * @return The paymentDate.
   */
  com.google.protobuf.Timestamp getPaymentDate();
  /**
   * <code>.google.protobuf.Timestamp payment_date = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getPaymentDateOrBuilder();
}
